vallejos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from .views import home

from apps.materiales.views import marcacomercialeditar, \
    materialeslistado, materialnuevo, materialeditar, \
    marcacomerciallistado, marcacomercialnueva, materialnuevosincodigo

from apps.stocks.views import stocklistado, stocknuevo, stockeditar

from apps.operaciones.views import (ajaxconsultamaterial, ajaxgrabaroperacion, operacioneditar,
    operacionlistado, operacionnueva)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('materialeslistado/', materialeslistado),
    path('materialnuevosincodigo/', materialnuevosincodigo),
    path('materialnuevo/', materialnuevo),
    path('materialeditar/<int:pk>', materialeditar),
    path('marcacomerciallistado/', marcacomerciallistado),
    path('marcacomercialnueva/', marcacomercialnueva),
    path('marcacomercialeditar/<int:pk>', marcacomercialeditar),
    path('operacionlistado/', operacionlistado),
    path('operacionnueva/', operacionnueva),
    path('operacioneditar/<int:pk>', operacioneditar),
    path('stocklistado/', stocklistado),
    path('stocknuevo/', stocknuevo),
    path('stockeditar/<int:pk>', stockeditar),

    path('ajaxconsultamaterial/', ajaxconsultamaterial),

    #path('ajaxmaterial/', ajaxmaterial),
    path('ajaxgrabaroperacion/', ajaxgrabaroperacion),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/stocks/models.py
from django.db import models

from apps.complementos_generales.models import Unidad
from apps.materiales.models import Material


class Stock(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    unidad = models.ForeignKey(Unidad, on_delete=models.CASCADE)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.material) + " - " + str(self.cantidad)

    class Meta:
        verbose_name_plural = "Stocks"
        unique_together = ('material','unidad')


# Create your models here.

apps/stocks/forms.py
from django import forms 

from apps.complementos_generales.models import Unidad
from apps.materiales.models import Material
from .models import Stock


class StockForm(forms.ModelForm):
    material = forms.ModelChoiceField(
        label="Material", queryset=Material.objects.all(), required=True)
    unidad = forms.ModelChoiceField(label="Unidad", queryset=Unidad.objects.all())
    cantidad = forms.DecimalField(label="Cantidad", required=True)

    class Meta:
        model = Stock
        fields = ["material", "unidad", "cantidad"]

apps/stocks/views.py
from django.db.models import Q
from django.contrib import messages
from django.core.files import File
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.shortcuts import render

from .forms import StockForm
from .models import Stock


def stocklistado(request):
    if 'txtBuscar' in request.GET:
        parametro = request.GET.get('txtBuscar')

        consulta = Stock.objects.filter(
            Q(material__codigo_barra=parametro) |
            Q(material__descripcion__icontains=parametro)
        ).order_by('material')

    else:
        consulta = Stock.objects.all().order_by('material')
    paginador = Paginator(consulta, 25)
    if "page" in request.GET:
        page = request.GET.get('page')
    else:
        page = 1
    resultados = paginador.get_page(page)
    
    return render(request, 'stocks/stock_list.html', {'resultados': resultados})


def stocknuevo(request):
    if request.POST:
        form = StockForm(request.POST)
        if form.is_valid():
            form.save()    
            messages.success(request, "SE HA GRABADO EL STOCK")
            return redirect('/stocklistado')
        else:
            return render(request, 'stocks/stock_edit.html', {"form": form})
    else:
        form = StockForm()
        return render(request, 'stocks/stock_edit.html', {"form": form})


def stockeditar(request, pk):
    consulta = Stock.objects.get(pk=pk)
    if request.POST:
        form = StockForm(request.POST, instance=consulta)
        if form.is_valid():
            form.save()
            messages.success(request, "SE HA ACTUALIZADO EL STOCK")
            return redirect('/stocklistado')
        else:
            return render(request, 'stocks/stock_edit.html', {"form": form})
    else:
        form = StockForm(instance=consulta)
        return render(request,
            'stocks/stock_edit.html',
            {"form": form}
        )


# Create your views here.

templates/stocks/stock_edit.html
{% extends 'base.html' %}

{% block content %}

    <div class="pure-g">
        <div class="pure-u-1-3"></div>
        <div class="pure-u-1-3">
            <h3>
                Busqueda/Alta y Edicion de Stock
            </h3>

            <form class="pure-form pure-form-aligned" method="POST">{% csrf_token %}
                <fieldset>
                    <div class="pure-control-group">
                        <label for="aligned-name">Material</label>
                        {{form.material}}
                        <span class="pure-form-message-inline">(*)Este dato es requerido.</span>
                    </div>

                    <div class="pure-control-group">
                        <label for="aligned-name">Unidad</label>
                        {{form.unidad}}
                        <span class="pure-form-message-inline">(*)Este dato es requerido.</span>
                    </div>

                    <div class="pure-control-group">
                        <label for="aligned-name">Cantidad</label>
                        {{form.cantidad}}
                        <span class="pure-form-message-inline">(*)Este dato es requerido.</span>
                    </div>

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Aceptar</button>
                        &nbsp; &nbsp; &nbsp;
                        <button type="button" class="pure-button" onclick="IrListadoMaterial()">Cancelar</button>
                    </div>
                </fieldset>                
            </form>
        </div>
        <div class="pure-u-1-3"></div>
    </div>

    {% block customjs %}

        <script>

            $(document).ready(function () {
                $("#id_material").select2();
            });
            
            function IrListadoMaterial() {
                window.location.replace("/materialeslistado");
            }
        </script>

    {% endblock %}

{% endblock %}

templates/stocks/stock_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="pure-g">
        <div class="pure-u-1-5"></div>
        <div class="pure-u-3-5">
            <h3>
                Busqueda de Stock
            </h3>

            <form class="pure-form">
                <fieldset>
                    <input type="text" id="txtBuscar" name="txtBuscar" placeholder="Buscar Item" />
                    <button type="submit" class="pure-button pure-button-primary">Buscar</button>

                    &nbsp;&nbsp;&nbsp;

                    <button type="button" class="pure-button pure-button" onclick="IrStockNuevo()">Nuevo</button>
                </fieldset>
            </form>  

        </div>
        <div class="pure-u-1-5"></div>
    </div>

    <br>
    <br>
    <br>

    <div class="pure-g">
        <div class="pure-u-1-24"></div>
        <div class="pure-u-22-24">
            <table class="pure-table pure-table-striped ">
                <thead>
                    <tr>
                        <th>Descripcion</th>
                        <th>Cantidad</th>
                        <th>Unidad</th>
                        <th>Editar</th>
                    </tr>

                </thead>
                <tbody>
                    
                    {% for resultado in resultados %}
                        <tr>
                            <td>{{resultado.material.descripcion.upper }}</td>
                            <td>{{resultado.cantidad}}</td>
                            <td>{{resultado.unidad}}</td>
                            <td>
                                <a href="/stockeditar/{{resultado.pk}} ">Editar</a></p>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="pure-u-1-24"></div>
    </div>
     
        
{% endblock %}


{% block customjs %}

    <script>

        $( document ).ready(function() {
            $("#txtBuscar").focus();
        });

        function IrStockNuevo() {
            window.location.replace("/stocknuevo");
        }
    </script>

{% endblock %}